version: '3.8'

services:

  # Main database used for the application
  db:
    image: mysql:8
    command: [ "mysqld", "--mysql-native-password=ON" ]
    container_name: mysql
    # If you change db details make sure docker/database/init.sql is updated!
    environment:
      MYSQL_ROOT_PASSWORD: "9RLbOmXmKIZcfdhCB1q2gdTkCwo7VXlkGCTYb"
      MYSQL_DATABASE: miluim
      MYSQL_USER: appUser
      MYSQL_PASSWORD: "9RLbOmXmKIZcfdhCB1q2gdTkCwo7VXlkGCTYb"
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "3306:3306"
    networks:
      - app-network


  # [IDF Service] Sails.js application
  idfservice:
    build: ./idfservice
    container_name: idfservice
    environment:
      NODE_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network


  # Nginx server used as a reverse proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Main Nginx configuration
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      # Certificates for SSL
      - ./docker/nginx/certs/certificate.pem:/etc/nginx/certs/certificate.pem
      - ./docker/nginx/certs/private-key.pem:/etc/nginx/certs/private-key.pem
      # Include server-specific configurations
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - idfservice
    networks:
      - app-network

volumes:
  db_data:


networks:
  app-network:
    driver: bridge
